public enum GameStates
{
    SettingUpBoard,
    PlaceFirstSettlement,
    PlaceFirstRoad,
    PlaceSecondSettlement,
    PlaceSecondRoad,
    RollOrUseDevCard,
    SelectMonopolyResource,
    FirstDevCardRoad,
    SecondDevCardRoad,
    SelectYearOfPlenty,
    PlaceRobber,
    SelectRobberTarget,
    SevenDiscardResources,
    TradeResponse,
    TradeReview,
    BuildOrTrade,
    GameOver
}
